### ISSUE TITLE
json help files

### ISSUE THREAD

**Issue by xoceunder** [jordanmueller/roku_channel#1]
@jordanmueller  json help files

**Comment by xoceunder** [comment]
@jordanmueller  help

**Comment by jordanmueller** [comment]
Hello @xoceunder 

What exactly do you meanby json help files? Do you mean Examples of JSON responses that this Roku Channel can parse to display content to a user?

**Comment by xoceunder** [comment]
It is not working json file

**Comment by xoceunder** [comment]
@jordanmueller  this not working

http://sjxm9203.xen.prgmr.com:8080/library/category/

**Comment by jordanmueller** [comment]
The hosting at prgmr.com was discontinued.  I re-deployed the app to heroku.  You can see content here:

https://evening-forest-8081.herokuapp.com/library/category/

I updated content.brs to use the new endpoints.

FYI:  This is hosted on the free tier of heroku.  This may not always be available due to daily limits.
